[program:inertia-ssr]
process_name=%(program_name)s_%(process_num)02d
command=php artisan inertia:start-ssr
directory=/var/www/html
autostart=true
autorestart=true
startsecs=0
stopwaitsecs=10
user=webuser
numprocs=1
